//
// Created by parallels on 9/30/19.
//

#ifndef VIDEOCOIN_PROOVING_SYSTEM_VERSION_H
#define VIDEOCOIN_PROOVING_SYSTEM_VERSION_H

#define VERSION "@PROJECT_VERSION@"

#endif //VIDEOCOIN_PROOVING_SYSTEM_VERSION_H
